# Generated by Django 4.1.1 on 2023-02-02 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=105)),
                ('car_model', models.CharField(max_length=50)),
                ('cust_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('car_number', models.CharField(max_length=25)),
                ('cust_addr', models.CharField(max_length=100)),
                ('Pickup_Date', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mech_name', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('Delivery_Date', models.DateField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.customer')),
            ],
        ),
    ]
