# Generated by Django 4.1.1 on 2023-02-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='customer',
            new_name='cust_name',
        ),
    ]
