# Generated by Django 4.1.1 on 2023-02-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_rename_cust_name_mechanic_car_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='car_number',
            new_name='cust_name',
        ),
    ]
